- hosts: 192.168.1.113
  tasks:
  - file:
     state: directory
     path: /dvd1

  - mount: 
     path: /dvd1
     src: /dev/sr0
     fstype: iso9660
     state: mounted

  - name: "Cofigure Yum"
    yum_repository:
     baseurl: /dvd1/AppStream
     name: mydvd1
     description: My dvd 1
     gpgcheck: no

  - name: "Cofigure Yum"
    yum_repository:
     baseurl: /dvd1/BaseOS
     name: mydvd2
     description: My dvd 2
     gpgcheck: no

  - name: "Cofigure Yum for docker"
    yum_repository:
     baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
     name: docker
     description: Docker repo
     gpgcheck: no

  - name: "Install docker"
    package:
     name: docker-ce-18.09.1-3.el7.x86_64
     state: present

  - name: "Install python"
    package:
     name: python36-3.6.8-1.module+el8+2710+846623d6.x86_64
     state: present

  - name: "Install docker python package"
    pip:
     name: "docker"

  - name: "Start docker service"
    service:
     name: docker
     state: started
     enabled: yes

  - name: Pull HTTPD image
    docker_image:
     name: httpd
     source: pull

  - name: "Copy web pages"
    copy:
     dest: /var/www/html/
     src: /root/Arth/Ansible/index.html

  - command: "systemctl start firewalld"

  - name: "Launch docker container"
    docker_container:
     name: "webserver"
     image: "httpd"
     ports: 
      - "182:80"
     state: started     
     volumes: /var/www/html/:/usr/local/apache2/htdocs/
 
  - name: "Disable firewall for port number"
    firewalld:
      port: 182/tcp
      state: enabled
      permanent: no
      immediate: yes

  - command: "systemctl stop firewalld"


